#code: language: ansible
---
- name: Install all apt packages
  become: True
  apt:
    pkg: sanoid
    force_apt_get: yes

- name: Upgrade all apt packages
  become: True
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Create directories if they do not exist
  become: True
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - /etc/sanoid

- name: Copy Sanoid config file and set owner and permissions
  become: True
  copy:
    src: sanoid.conf
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: 0644
