[main-rust/nextcloud]
	use_template = nextcloud
	recursive = yes
	process_children_only = yes

[main-rust/backups]
	use_template = backups
	recursive = yes
	process_children_only = yes

[main-rust/media]
	use_template = media
	recursive = yes
	process_children_only = yes

#############################
# templates below this line #
#############################

[template_backups]
    frequently = 0
    hourly = 0
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes

[template_nextcloud]
    frequently = 0
    hourly = 24
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes

[template_media]
    frequently = 0
    hourly = 0
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes