#! /bin/bash

# Use eza instead of ls
alias l='eza -lbF --git  --sort=type'
alias la='eza -lbhHigUmuSa --sort=type --time-style=long-iso --git --color-scale'
alias ll='eza -lbGF --git  --sort=type'
alias llm='eza -lbGd --git --sort=modified'
alias ls='eza --sort=type'
alias lx='eza -lbhHigUmuSa@ --sort=type  --time-style=long-iso --git --color-scale'

# Use bat instead of cat
alias cat='bat --paging=never'
